# Load data from Github ⚙️

## `0_scraping`

### Read the Dataframe with  coordinates

In [3]:
import pandas as pd
import requests
from io import BytesIO

# URL of the pickled DataFrame in the GitHub repository
url = "https://raw.githubusercontent.com/Selimmmm/spe1/fff081c86c6c17ae30b96f0f250f2c90cabfd09c/projets/projet_III/data/df_with_coordinates_str.pk"

# Make a request to get the pickled file
response = requests.get(url)

# Convert the binary response content to a BytesIO object
data = BytesIO(response.content)

# Use pandas to read the pickled DataFrame from the BytesIO object
df = pd.read_pickle(data)
df

,temperature_text,color_code,url_suffix,temperature,coordinates_str
0,51.3 °C (124.3 °F)\n,#770000,/wiki/Ouargla,51.3,"(31°57′N, 5°19′E)"
1,44.0 °C (111.2 °F)\n,#DC0000,"/wiki/Maun,_Botswana",44.0,"(19°59′S, 023°25′E)"
2,47.2 °C (117.0 °F)\n,#B00000,"/wiki/Dori,_Burkina_Faso",47.2,"(14°02′N, 0°02′W)"
3,48.0 °C (118.4 °F)\n,#A50000,/wiki/Faya-Largeau,48.0,"(17°55′01″N, 19°7′0″E)"
4,36.0 °C (96.8 °F)\n,#FF2500,/wiki/Prince_Said_Ibrahim_International_Airport,36.0,"(11°32′12″S, 43°16′17″E)"
...,...,...,...,...,...
141,38.0 °C (100.4 °F)\n,#FF1800,/wiki/Saint-Laurent-du-Maroni,38.0,"(5°29′58″N, 54°01′52″W)"
142,46.2 °C (115.2 °F)\n,#BE0000,/w/index.php?title=Las_Palmas_(Paraguay)&actio...,46.2,"(None, None)"
143,41.6 °C (106.9 °F)\n,#FD0000,/wiki/I%C3%B1apari,41.6,"(10°56′51.64″S, 69°34′35.04″W)"
144,44.0 °C (111.2 °F)\n,#DC0000,/wiki/Paysand%C3%BA,44.0,"(32°19′17″S, 58°4′32″W)"
145,43.6 °C (110.5 °F)\n,#E20000,/wiki/Santa_Ana_de_Coro,43.6,"(11°25′01″N, 69°40′12″W)"

## `1_plotting.ipynb`

### Read the Dataframe with cleaned coordinates

In [10]:
import pandas as pd
import requests
from io import BytesIO

# URL of the pickled DataFrame in the GitHub repository
url = "https://raw.githubusercontent.com/Selimmmm/spe1/fff081c86c6c17ae30b96f0f250f2c90cabfd09c/projets/projet_III/data/df_with_coordinates_cleaned.pk"

# Make a request to get the pickled file
response = requests.get(url)

# Convert the binary response content to a BytesIO object
data = BytesIO(response.content)

# Use pandas to read the pickled DataFrame from the BytesIO object
df = pd.read_pickle(data)
df

,temperature_text,color_code,url_suffix,temperature,coordinates_str,lat,long
0,51.3 °C (124.3 °F)\n,#770000,/wiki/Ouargla,51.3,"(31°57′N, 5°19′E)",31.950000,5.316667
1,44.0 °C (111.2 °F)\n,#DC0000,"/wiki/Maun,_Botswana",44.0,"(19°59′S, 023°25′E)",-19.983333,23.416667
2,47.2 °C (117.0 °F)\n,#B00000,"/wiki/Dori,_Burkina_Faso",47.2,"(14°02′N, 0°02′W)",14.033333,-0.033333
3,48.0 °C (118.4 °F)\n,#A50000,/wiki/Faya-Largeau,48.0,"(17°55′01″N, 19°7′0″E)",17.916944,19.116667
4,36.0 °C (96.8 °F)\n,#FF2500,/wiki/Prince_Said_Ibrahim_International_Airport,36.0,"(11°32′12″S, 43°16′17″E)",-11.536667,43.271389
...,...,...,...,...,...,...,...
141,38.0 °C (100.4 °F)\n,#FF1800,/wiki/Saint-Laurent-du-Maroni,38.0,"(5°29′58″N, 54°01′52″W)",5.499444,-54.031111
142,46.2 °C (115.2 °F)\n,#BE0000,/w/index.php?title=Las_Palmas_(Paraguay)&actio...,46.2,"(None, None)",NaN,NaN
143,41.6 °C (106.9 °F)\n,#FD0000,/wiki/I%C3%B1apari,41.6,"(10°56′51.64″S, 69°34′35.04″W)",-10.947678,-69.576400
144,44.0 °C (111.2 °F)\n,#DC0000,/wiki/Paysand%C3%BA,44.0,"(32°19′17″S, 58°4′32″W)",-32.321389,-58.075556
145,43.6 °C (110.5 °F)\n,#E20000,/wiki/Santa_Ana_de_Coro,43.6,"(11°25′01″N, 69°40′12″W)",11.416944,-69.670000

## `2_modeling.ipynb`

In [11]:
import requests
from io import StringIO

url ="https://raw.githubusercontent.com/Selimmmm/spe1/fff081c86c6c17ae30b96f0f250f2c90cabfd09c/projets/projet_III/data/GlobalTemperatures.csv"
response = requests.get(url)
s = str(response.content, 'utf-8')
data = StringIO(s)
temperatures = pd.read_csv(data)
temperatures

,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
0,1750-01-01,3.034,3.574,NaN,NaN,NaN,NaN,NaN,NaN
1,1750-02-01,3.083,3.702,NaN,NaN,NaN,NaN,NaN,NaN
2,1750-03-01,5.626,3.076,NaN,NaN,NaN,NaN,NaN,NaN
3,1750-04-01,8.490,2.451,NaN,NaN,NaN,NaN,NaN,NaN
4,1750-05-01,11.573,2.072,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3187,2015-08-01,14.755,0.072,20.699,0.110,9.005,0.170,17.589,0.057
3188,2015-09-01,12.999,0.079,18.845,0.088,7.199,0.229,17.049,0.058
3189,2015-10-01,10.801,0.102,16.450,0.059,5.232,0.115,16.290,0.062
3190,2015-11-01,7.433,0.119,12.892,0.093,2.157,0.106,15.252,0.063
3191,2015-12-01,5.518,0.100,10.725,0.154,0.287,0.099,14.774,0.062